package com.github.tornado2023team5.kanjichan.model.function;

public enum CommandType {
    MAKE_PLAN,
    SET_LOCATION,
    SEARCH_SPOTS,
    REMOVE_SPOT,
    ADOPT_SPOTS,
    MAKE_DRAFT,
    DECIDE_DRAFT,
    EDIT_AND_ADD_SPOT_TO_DECIDED_DRAFT,
    EDIT_AND_REMOVE_SPOT_FROM_DECIDED_DRAFT,
    EDIT_AND_CHANGE_SPOT_FROM_DECIDED_DRAFT,
    NONE
}
