services:
  java:
    working_dir: /opt
    image: gradle:latest
    env_file: ./.env
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - gradle-cache:/root/.gradle
      - ./JavaBE/build/libs/Kanjichan-0.0.1.jar:/opt/Kanjichan.jar
    command: ["java", "-jar", "Kanjichan.jar"]

volumes:
  gradle-cache: